apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: result
  name: result
  namespace: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: result
    spec:
      containers:
      - image: 192.168.44.44:8082/docker-local/backend:latest
        name: backend
        ports:
        - containerPort: 5001
        resources: {}
      imagePullSecrets:
      - name: regcred
status: {}
